name: Deploy to EC2

on:
  push:
    branches: [ "master" ]  # master 브랜치에 push가 발생하면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Setup Remote Directory
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-124-59-140.ap-northeast-2.compute.amazonaws.com
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/app
            chmod 755 ~/app

      - name: Copy JAR file via SSH
        uses: appleboy/scp-action@master
        with:
          host: ec2-13-124-59-140.ap-northeast-2.compute.amazonaws.com
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "~/app"
          strip_components: 2
          debug: true

      - name: Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-124-59-140.ap-northeast-2.compute.amazonaws.com
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: "20m"
          debug: true
          script: |
            cd ~/app || exit 1
            echo "Current directory: $(pwd)"
            echo "Listing directory contents:"
            ls -la
            
            echo "Checking for existing Java processes..."
            EXISTING_PID=$(pgrep -f '.jar' || true)
            if [ ! -z "$EXISTING_PID" ]; then
              echo "Killing process $EXISTING_PID"
              kill $EXISTING_PID || true
              sleep 2
            else
              echo "No existing Java process found"
            fi
            
            echo "Starting new application..."
            JAR_FILE=$(ls -1 *SNAPSHOT.jar | grep -v plain || ls -1 *.jar)
            echo "Using JAR file: $JAR_FILE"
            chmod +x "$JAR_FILE"
            
            # 백그라운드에서 애플리케이션 실행
            nohup java -jar "$JAR_FILE" > app.log 2>&1 &
            APP_PID=$!
            
            echo "Application started with PID: $APP_PID"
            echo "Waiting for application to start..."
            sleep 10
            
            # 프로세스가 실행 중인지 확인
            if ps -p $APP_PID > /dev/null; then
              echo "Application is running successfully with PID: $APP_PID"
              echo "Recent log output:"
              tail -n 20 app.log
              exit 0
            else
              echo "Application failed to start"
              echo "Log output:"
              cat app.log
              exit 1
            fi 