name: Deploy to EC2

on:
  push:
    branches: [ "master" ]  # main 브랜치에 push가 발생하면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Copy JAR file via SSH
        uses: appleboy/scp-action@master
        with:
          host: ec2-13-124-59-140.ap-northeast-2.compute.amazonaws.com
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "~/app"
          strip_components: 2

      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-124-59-140.ap-northeast-2.compute.amazonaws.com
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app
            pkill -f '.jar' || true
            nohup java -jar *.jar > app.log 2>&1 & 